# Introduction to TensorFlow

[TensorFlow](https://www.tensorflow.org) is a free and open-source library, maintained by Google. TensorFlow was designed for differentiable programming and dataflow tasks, which allows us to implement neural networks and machine learning algorithms utilizing the library.

TensorFlow is written in C, with Python wrappers and ports to JavaScript, C++, C#, Swift and Julia. TensorFlow allows users to create static dataflow graphs with operations associated to nodes and run the graph at execution. Later verions of TensorFlow use [Eager Execution](https://www.tensorflow.org/guide/eager) abstract the graph creation, allowing users to program the networks "on the go".


The  Python TensorFlow ecosystem allows users to use the library using two interfaces:
* ```tf.keras```: The high level API, with pythonic syntax and better readability. A lot of the graph construction and mathematics is abstracted into Keras methods.
* ```tf```: The low level API, allows users to create dataflow graphs and tune them. Requires deeper insight into programming and mathematics.
---

## 1. Tensors: Declaration of tensors and simple tensor operations

A tensor is a generalization of scalars, vectors and matrices to an arbitrary number of indices\[[WolframAlpha](https://www.wolframalpha.com/input/?i=tensor)\]. In computational terms, we represent tensors as $n$-dimensional arrays. Tensors are useful to describe the multilinear relationships between a set of algebraic objects in a vector space.

TensorFlow creates dataflow graphs, as described in the introduction. Each node is associated with an operation, which is conditionally performed on an input. The data that flows through the graph is defined in forms of the following tensors:

* **Scalar:** A scalar is a rank zero tensor that contains only numerical magnitude. 

* **Vector:** A vector is a rank one tensor that contains numerical magnitude and a direction that relates it to other tensors. 

* **Matrix:** A matrix is ranked 2 an dis considered a table of relations between vectors in the vector space. 

* **n-Dimensional Tensor:** $n$-Dimensional tensors (represented in memory as an array of arrays, $n$-times) are useful for storing high dimensional data, such as multi-channel images(RGBa).

TensorFlow supports the standard python data types bh default. However, there are a few extra data types for representing complex numbers and quantized integers.
For a complete list of data types supported by TensorFlow, visit (https://www.tensorflow.org/api_docs/python/tf/dtypes/DType).

**Declaring tensors**

In the following section, the syntax for declaring tensors is discussed.

In [3]:
# Import necessary libraries
import tensorflow as tf
import numpy as np

In [4]:
# Store Euler's number as a scalar float
scalar = tf.Variable(2.7182818284, tf.float64)

# Store Hello, World into a string vector
vector = tf.Variable(["Hello", "World"], tf.string)

# Define 3*3 matrices, one containing 9 odd numbers and the other containing 9 even numbers
mat_1 = tf.Variable([[1, 3, 5], [7, 9, 11], [13, 15, 17]], tf.int16)
mat_2 = tf.Variable([[2, 4, 6], [8, 10, 12], [14, 16, 18]], tf.int16)

# Define a 4-dimensional tensor that contains an image in the format batch x height x width x color
# The image is initialized using tensorflow.zeros, which initializes all elements in a tensor to 0
# An alternative is to use the tensorflow.ones command to set all values to 1
img_tensor = tf.zeros([5, 32, 32, 3])


The data a tensor contains can be viewed using one of the following methods:

In [6]:
# python print statement
print(mat_2)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>


In [5]:
# tensorflow.rank
tf.rank(mat_1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
# tensorflow.shape
tf.shape(img_tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 32, 32,  3], dtype=int32)>

The three methods produce significantly different outputs, with the rank method only returning the rank and data type of the tensor, while the shape returns the shape, the dimensions and the data type.
The print statement displays the entire tensor, whichis not ideal when working with large tensors, such as arrays of images.

It is also possible to slice tensors using the same indexing logic as in numpy arrays.

In [28]:
mat_slc_1 = mat_1[0]
print(mat_slc_1)
mat_slc_2 = mat_2[:,2]
print(mat_slc_2)

tf.Tensor([1 3 5], shape=(3,), dtype=int32)
tf.Tensor([ 6 12 18], shape=(3,), dtype=int32)


In the following code blocks, basic tensor operations are reviewed:

In [34]:
# Elementwise addition
add_mat = tf.add(mat_1, mat_2)
print("\nElementwise Addition:\n", add_mat)

# Elementwise subtraction
add_mat = tf.subtract(mat_1, mat_2)
print("\nElementwise Subtraction:\n", add_mat)

# Matrix multiplication
add_mat = tf.matmul(mat_1, mat_2)
print("\nMatrix multiplication:\n", add_mat)


Elementwise Addition:
 tf.Tensor(
[[ 3  7 11]
 [15 19 23]
 [27 31 35]], shape=(3, 3), dtype=int32)

Elementwise Subtraction:
 tf.Tensor(
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]], shape=(3, 3), dtype=int32)

Matrix multiplication:
 tf.Tensor(
[[ 96 114 132]
 [240 294 348]
 [384 474 564]], shape=(3, 3), dtype=int32)


In [36]:
# Transpose of a matrix
print("Original Matrix:\n", mat_2)
print("\nMatrix Transpose:\n", tf.transpose(mat_2))

Original Matrix:
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>

Matrix Transpose:
 tf.Tensor(
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]], shape=(3, 3), dtype=int32)


Similarly, functions for most mathematical operations are available built into the package. The full list of functions can be found in the [tf.math](https://www.tensorflow.org/api_docs/python/tf/math) module.

---

## 2. Binary classification

In [37]:
import tensorflow_datasets as tfds
# tfds.

In [38]:
tfds.list_builders()

['abstract_reasoning',
 'aeslc',
 'aflw2k3d',
 'amazon_us_reviews',
 'arc',
 'bair_robot_pushing_small',
 'big_patent',
 'bigearthnet',
 'billsum',
 'binarized_mnist',
 'binary_alpha_digits',
 'c4',
 'caltech101',
 'caltech_birds2010',
 'caltech_birds2011',
 'cars196',
 'cassava',
 'cats_vs_dogs',
 'celeb_a',
 'celeb_a_hq',
 'chexpert',
 'cifar10',
 'cifar100',
 'cifar10_1',
 'cifar10_corrupted',
 'citrus_leaves',
 'cityscapes',
 'civil_comments',
 'clevr',
 'cmaterdb',
 'cnn_dailymail',
 'coco',
 'coil100',
 'colorectal_histology',
 'colorectal_histology_large',
 'cos_e',
 'curated_breast_imaging_ddsm',
 'cycle_gan',
 'deep_weeds',
 'definite_pronoun_resolution',
 'diabetic_retinopathy_detection',
 'dmlab',
 'downsampled_imagenet',
 'dsprites',
 'dtd',
 'duke_ultrasound',
 'dummy_dataset_shared_generator',
 'dummy_mnist',
 'emnist',
 'esnli',
 'eurosat',
 'fashion_mnist',
 'flic',
 'flores',
 'food101',
 'gap',
 'gigaword',
 'glue',
 'groove',
 'higgs',
 'horses_or_humans',
 'i_natura